#source('/Volumes/datasets_1/human_sequence_prostate_WGBS/reproduce/scripts/2019_05_15_prepare_environment.r')

# Plots figure 4A

#TODO: Debug this and actually build the plot in this file

library(ggplot2)
library(stringr)
library(ggpubr)

fdrcut <- 0.05

#This is the p-value which corresponds to an FDR of 0.05 looking only at
#Genebody/promoter eHMRs
pcutpromgene <- 0.01238332

#Load in file with expr correlated to DNA alterations, methylation generated by summary_expr.txt
filename <- '../methylseq/hmrseg/summary_expr.txt'
sumexpr <- read.table(filename,sep='\t',stringsAsFactors=F,header=T,row.names=1)
rownames(sumexpr) <- str_split_fixed(rownames(sumexpr),'\\.',2)[,1]
totalgenes <- dim(sumexpr)[1]

#Load in PCa vs other comparisons from TCGA pancan
filename <- 'wgbs/tcga_pancan/pca_specific.tsv'
pcaspec <- read.table(filename,sep='\t',stringsAsFactors=F,header=T,row.names=1)
rownames(pcaspec) <- str_split_fixed(rownames(pcaspec),'\\.',2)[,1]

#Figure out which genes are actually PCa specific
pcaspec$PRAD_p <- NULL
pcaspec$FPPP_p <- NULL
pcaspec$count <- 0
realn <- dim(pcaspec)[1]#*33
for(i in 11:42) {
    fdrcol <- p.adjust(pcaspec[,i],method='fdr',n=realn)
    pcaspec$count <- pcaspec$count+as.numeric(fdrcol<=fdrcut)
}
pvb_fdr_new <- p.adjust(pcaspec$pvb,method='fdr',n=realn)
rowsspec <- pcaspec$count>=32 & pvb_fdr_new<=fdrcut & pcaspec$fc_a>=2
print(sum(rowsspec))

siggenes <- pcaspec[rowsspec,'gene']
print(length(siggenes))
commongenes <- intersect(rownames(pcaspec)[rowsspec],rownames(sumexpr))
sumexpr$PCa_specific <- F
sumexpr[commongenes,'PCa_specific'] <- T

#Calculate FDRs for DNA alterations, mutations
sumexpr$svfdr <- p.adjust(sumexpr$svp,method='fdr')
sumexpr$cnfdr <- p.adjust(sumexpr$cnp,method='fdr')
sumexpr$mutfdr <- p.adjust(sumexpr$mutp,method='fdr')
sumexpr$anovafdr <- p.adjust(sumexpr$anovap,method='fdr')
sumexpr$sd <- apply(log2(tpm[rownames(sumexpr),samples_wgbs]+1),1,sd)
sumexpr$meanexpr <- rowMeans(tpm[rownames(sumexpr),samples_wgbs],na.rm=T)
sumexpr$genewidth <- sumexpr$end-sumexpr$start

#write.table(sumexpr,'C:/Users/Admin/Desktop/volcano.tsv',col.names=NA,row.names=T,quote=F,sep='\t')

#Used to be use to determine what in the top-left corner of volcano to show
#I kept this just to print out those genes
corcut <- quantile(abs(sumexpr$methylcor),0.995,na.rm=T)
sdcut <- quantile(abs(sumexpr$sd),0.995,na.rm=T)
print(corcut)
print(sdcut)

rowsmethylsig <- sumexpr$methylp<=pcutpromgene
rowsdnasig <- sumexpr$svfdr<=fdrcut | sumexpr$cnfdr<=fdrcut | sumexpr$mutfdr<=fdrcut
rowsanovasig <- sumexpr$anovafdr<=fdrcut
rowsmethylsig[is.na(rowsmethylsig)] <- F
rowsdnasig[is.na(rowsdnasig)] <- F
rowsanovasig[is.na(rowsanovasig)] <- F
names(rowsanovasig) <- rownames(sumexpr)

print(sum(sumexpr$PCa_specific & rowsdnasig))
print(sum(sumexpr$PCa_specific & rowsmethylsig))
print(sum(sumexpr$PCa_specific))
stopifnot(F)

rowshighlight <- rowsanovasig & rowsmethylsig &
    abs(sumexpr$methylcor)>=corcut & sumexpr$sd>=sdcut
rowshighlight[is.na(rowshighlight)] <- F

#Plot the volcano plot
sumexpr$group <- ''
sumexpr[sumexpr$PCa_specific,'group'] <- 'PCa specific'
genes2keep <- c('SLC45A3','SCHLAP1','SPON2','PCAT14','TMEFF2','TDRD1')
sumexpr[sumexpr$name%in%genes2keep,'group'] <- sumexpr[sumexpr$name%in%genes2keep,'name']
print(sumexpr[rowshighlight,c('name','methylcor','sd','meanexpr','PCa_specific')])

sumexpr <- sumexpr[order(sumexpr$group),]

lmcor <- lm(methylcor~meanexpr+sd+genewidth+PCa_specific,sumexpr)
print(summary(lmcor))

print('Plotting')
plist <- list()
colors <- c('darkgray','black','green','blue','purple','yellow','orange','red')
plist[[2]] <- ggplot(sumexpr,aes(x=methylcor,y=sd,color=group,shape=PCa_specific,alpha=group)) + 
    geom_point(size=2)+theme_classic()+xlab('Spearman\'s rho')+ylab('Log2(TPM+1) SD')+
    scale_alpha_manual(guide='none',values=list(0.2,1,1,1,1,1,1,1))+
    scale_colour_manual(values=colors)+
    #geom_segment(x=(-corcut+0.01),y=sdcut,xend=(-corcut+0.01)-0.2,yend=sdcut,color='black')+
    #geom_segment(x=(-corcut+0.01),y=sdcut,xend=(-corcut+0.01),yend=sdcut+1.5,color='black')+
    geom_vline(xintercept=0,color='black')+
    scale_y_continuous(limits=c(0,5))
#geom_text(data=sumexpr[rowshighlight,],aes(methylcor,sd,label=name),nudge_y=0.1)

test <- wilcox.test(sumexpr$sd~sumexpr$PCa_specific)
plist[[1]] <- ggplot(sumexpr,aes(x=PCa_specific,y=sd))+
    xlab('')+ylab('')+ggtitle(paste('Wilcox p:',signif(test$p.value,4)))+
    geom_boxplot()+theme_classic()
plist[[3]] <- ggplot() + theme_void()
test <- wilcox.test(sumexpr$methylcor~sumexpr$PCa_specific)
plist[[4]] <- ggplot(sumexpr,aes(x=PCa_specific,y=methylcor))+
    xlab('')+ylab('')+ggtitle(paste('Wilcox p:',signif(test$p.value,4)))+
    geom_boxplot()+theme_classic()+coord_flip()

ggarrange(plotlist=plist,widths=c(1,4),heights=c(4,1))
ggsave('C:/Users/Admin/Desktop/volcano.pdf',width=13,height=10,useDingbats=F)
dev.off()

#Print out a table with the pathway enrichment of eHMRs
print(paste('# Methyl:',sum(rowsmethylsig,na.rm=T)))
print(paste('# DNA:',sum(rowsdnasig,na.rm=T)))
print(paste('# DNA & Methyl:',sum(rowsmethylsig & rowsdnasig,na.rm=T)))
print(paste('% Methyl adds to DNA:',sum(rowsanovasig,na.rm=T)/totalgenes))

dfplot <- data.frame()
dfplot[1,'percent'] <- sum(rowsanovasig,na.rm=T)/totalgenes
dfplot[1,'group'] <- 'Total'

geneshk <- rownames(sumexpr)[sumexpr$name %in% housekeeping]
sighk <- sum(rowsanovasig[geneshk],na.rm=T)
dfplot[2,'percent'] <- sighk/length(geneshk)
dfplot[2,'group'] <- 'Housekeeping'
tabhk <- c(sighk,length(geneshk)-sighk)

genescosmic <- rownames(sumexpr)[sumexpr$name %in% cosmicgenes]
siggosmic <- sum(rowsanovasig[genescosmic],na.rm=T)
dfplot[3,'percent'] <- siggosmic/length(genescosmic)
dfplot[3,'group'] <- 'COSMIC'
tabcosmic <- rbind(tabhk,c(siggosmic,length(genescosmic)))
dfplot[3,'p'] <- fisher.test(tabcosmic)$p.value

print(setdiff(pca_cell_genes,sumexpr$name))
genescell <- rownames(sumexpr)[sumexpr$name %in% pca_cell_genes]
sigcell <- sum(rowsanovasig[genescell],na.rm=T)
dfplot[4,'percent'] <- sigcell/length(genescell)
dfplot[4,'group'] <- 'PCa Genes'
tabcell <- rbind(tabhk,c(sigcell,length(genescell)))

print(dfplot)

#This was for GSEA pre-ranked
#logp <- -log10(sumexpr$anovap)
#logp[is.na(logp)] <- 0
#gsea <- cbind.data.frame(sumexpr$name,logp)
#write.table(gsea,'C:/Users/Admin/Desktop/add2dna.rnk',col.names=F,row.names=F,quote=F,sep='\t')

for(i in 1:length(data.pathways)) {
    if(i%%100==0) print(i)
    genesi <- rownames(sumexpr)[sumexpr$name %in% data.pathways[[i]]]
    sigi <- sum(rowsanovasig[genesi],na.rm=T)
    dfplot[i+4,'percent'] <- sigi/length(genesi)
    dfplot[i+4,'group'] <- names(data.pathways)[i]
    tabi <- rbind(tabhk,c(sigi,length(genesi)))
    dfplot[i+4,'p'] <- fisher.test(tabi)$p.value
}
dfplot$fdr <- p.adjust(dfplot$p,method='fdr')
dfplot <- dfplot[rev(order(dfplot$percent)),]
write.table(dfplot,'C:/Users/Admin/Desktop/add2dna.tsv',col.names=T,row.names=F,quote=F,sep='\t')

#OLD plot to make histogram of linear model fits with DNA vs. DNA+methylation
#br <- c(-100,(1:10/10))
#histdna <- hist(sumexpr$dna_r2,breaks=br,plot=F)
#histmethyl <- hist(sumexpr$methyl_r2,breaks=br,plot=F)
#freqs <- factor((1:10)/10)
#histdf <- rbind.data.frame(
#	cbind.data.frame(freq=freqs,count=histdna$counts,group='DNA'),
#	cbind.data.frame(freq=freqs,count=histmethyl$counts,group='DNA+Methyl'))
#ggplot(histdf,aes(x=freq,y=count,fill=group)) + 
#	geom_bar(stat='identity',position='dodge')
#ggsave('C:/Users/Admin/Desktop/add2dna.pdf')
