#source('/Volumes/datasets_1/human_sequence_prostate_WGBS/reproduce/scripts/2019_05_15_prepare_environment.r')

# Plots figure 3A

fdrcut = 0.05

#This is the p-value which corresponds to an FDR of 0.05 looking only at
#Genebody/promoter eHMRs
pcutpromgene = 0.01238332

#Load in file with expr correlated to DNA alterations, methylation generated by summary_expr.txt
sumexpr = read.table(fn_hmr_summary_expr, sep='\t', stringsAsFactors=FALSE,
                     header=TRUE, row.names=1)
rownames(sumexpr) = str_split_fixed(rownames(sumexpr),'\\.',2)[,1]
totalgenes = dim(sumexpr)[1]

#Load in PCa vs other comparisons from TCGA pancan
pcaspec = read.table(fn_pca_specific,sep='\t',stringsAsFactors=F,header=T,row.names=1)
rownames(pcaspec) = str_split_fixed(rownames(pcaspec),'\\.',2)[,1]

#Figure out which genes are actually PCa specific
pcaspec$PRAD_p = NULL
pcaspec$FPPP_p = NULL
pcaspec$count = 0
realn = dim(pcaspec)[1]#*33

for(i in 11:42) {
    fdrcol = p.adjust(pcaspec[,i],method='fdr',n=realn)
    pcaspec$count = pcaspec$count+as.numeric(fdrcol<=fdrcut)
}
pvb_fdr_new = p.adjust(pcaspec$pvb,method='fdr',n=realn)
rowsspec = pcaspec$count>=32 & pvb_fdr_new<=fdrcut & pcaspec$fc_a>=2
print(sum(rowsspec))

siggenes = pcaspec[rowsspec,'gene']
print(length(siggenes))
commongenes = intersect(rownames(pcaspec)[rowsspec],rownames(sumexpr))
sumexpr$PCa_specific = F
sumexpr[commongenes,'PCa_specific'] = T

#Calculate FDRs for DNA alterations, mutations
sumexpr$svfdr = p.adjust(sumexpr$svp,method='fdr')
sumexpr$cnfdr = p.adjust(sumexpr$cnp,method='fdr')
sumexpr$mutfdr = p.adjust(sumexpr$mutp,method='fdr')
sumexpr$anovafdr = p.adjust(sumexpr$anovap,method='fdr')
sumexpr$sd = apply(log2(tpm[rownames(sumexpr),sample_ids_wgbs]+1),1,sd)
sumexpr$meanexpr = rowMeans(tpm[rownames(sumexpr),sample_ids_wgbs],na.rm=T)
sumexpr$genewidth = sumexpr$end-sumexpr$start

corcut = quantile(abs(sumexpr$methylcor),0.995,na.rm=T)
sdcut = quantile(abs(sumexpr$sd),0.995,na.rm=T)
print(corcut)
print(sdcut)

rowsmethylsig = sumexpr$methylp<=pcutpromgene
rowsdnasig = sumexpr$svfdr<=fdrcut | sumexpr$cnfdr<=fdrcut | sumexpr$mutfdr<=fdrcut
rowsanovasig = sumexpr$anovafdr<=fdrcut
rowsmethylsig[is.na(rowsmethylsig)] = F
rowsdnasig[is.na(rowsdnasig)] = F
rowsanovasig[is.na(rowsanovasig)] = F
names(rowsanovasig) = rownames(sumexpr)

print(sum(sumexpr$PCa_specific & rowsdnasig))
print(sum(sumexpr$PCa_specific & rowsmethylsig))
print(sum(sumexpr$PCa_specific))

rowshighlight = rowsanovasig & rowsmethylsig &
    abs(sumexpr$methylcor)>=corcut & sumexpr$sd>=sdcut
rowshighlight[is.na(rowshighlight)] = F


#Print out a table with the pathway enrichment of eHMRs
print(paste('# Methyl:',sum(rowsmethylsig,na.rm=T)))
print(paste('# DNA:',sum(rowsdnasig,na.rm=T)))
print(paste('# DNA & Methyl:',sum(rowsmethylsig & rowsdnasig,na.rm=T)))
print(paste('% Methyl adds to DNA:',sum(rowsanovasig,na.rm=T)/totalgenes))


dfplot = data.frame()
dfplot[1,'percent'] = sum(rowsanovasig,na.rm=TRUE)/totalgenes
dfplot[1,'group'] = 'Total'

geneshk = rownames(sumexpr)[sumexpr$name %in% genelist_housekeeping]
sighk = sum(rowsanovasig[geneshk],na.rm=T)
dfplot[2,'percent'] = sighk/length(geneshk)
dfplot[2,'group'] = 'Housekeeping'
tabhk = c(sighk,length(geneshk)-sighk)

genescosmic = rownames(sumexpr)[sumexpr$name %in% genelist_cosmic]
siggosmic = sum(rowsanovasig[genescosmic],na.rm=TRUE)
dfplot[3,'percent'] = siggosmic/length(genescosmic)
dfplot[3,'group'] = 'COSMIC'
tabcosmic = rbind(tabhk,c(siggosmic,length(genescosmic)))
dfplot[3,'p'] = fisher.test(tabcosmic)$p.value

print(setdiff(genelist_pca_cell_genes,sumexpr$name))
genescell = rownames(sumexpr)[sumexpr$name %in% genelist_pca_cell_genes]
sigcell = sum(rowsanovasig[genescell],na.rm=T)
dfplot[4,'percent'] = sigcell / length(genescell)
dfplot[4,'group'] = 'PCa Genes'
tabcell = rbind(tabhk,c(sigcell,length(genescell)))
dfplot[4,'p'] = fisher.test(tabcell)$p.value

print(dfplot)

n_in_pathway = c( totalgenes, length(geneshk), length(genescosmic), rep(0, length(data.pathways)) )
for(i in 1:length(data.pathways)) {
    if(i%%100==0) print(i)
    genesi = rownames(sumexpr)[sumexpr$name %in% data.pathways[[i]]]
    sigi = sum(rowsanovasig[genesi],na.rm=T)
    dfplot[i+3,'percent'] = sigi/length(genesi)
    n_in_pathway[i+3] = length(genesi)
    dfplot[i+3,'group'] = names(data.pathways)[i]
    tabi = rbind(tabhk,c(sigi,length(genesi)))
    dfplot[i+3,'p'] = fisher.test(tabi)$p.value
}
dfplot$fdr = p.adjust(dfplot$p,method='fdr')
dfplot$n_in_pathway = n_in_pathway
dfplot = dfplot[rev(order(dfplot$percent)),]
#write.table(dfplot,'C:/Users/Admin/Desktop/add2dna.tsv',col.names=T,row.names=F,quote=F,sep='\t')

layout(matrix(1,1,1))
dfplot = dfplot[order(dfplot$percent),]
dfplot$percent=round(dfplot$percent*100, 2)
colors=rep("grey", dim(dfplot)[1])
colors[ dfplot$group=="ANDROGEN_RESPONSE"] = "red"
colors[ dfplot$group=="Total"] = "black"
colors[ dfplot$group=="Housekeeping"] = "darkblue"
text_color = rep("black", dim(dfplot)[1])
text_color[ dfplot$group=="ANDROGEN_RESPONSE"] = "white"
text_color[ dfplot$group=="Total"] = "white"
text_color[ dfplot$group=="Housekeeping"] = "white"


par(mar=c(2,5,1,1))
b=barplot( dfplot$percent, xaxs="i", ylab="% of genes in pathway", ylim=c(-25,80), xlim=c(0, 60),
         col=colors, axes=FALSE)
axis(2, at=seq(from=0, to=80, by=10), labels = seq(from=0, to=80, by=10), las=1 )
idx = which( dfplot$fdr < 0.05 )
text( b[idx], dfplot$percent[idx]+2, "*", font=2, cex=2)
text( b, rep(1,dim(dfplot)[1]), dfplot$n_in_pathway, cex=0.75, srt=90, font=1, col=text_color, adj=0  )
text( b, rep(-1,dim(dfplot)[1]), tolower(dfplot$group), cex=0.6, srt=90, font=1, srt=-45, adj=0  )
